services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIX_ENV: "${MIX_ENV}"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
