name: Website Active
on:
  push:
    paths:
      - '.github/workflows/status.yml'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
env:
  CHAT_URL: 'https://broken-shape-8192.fly.dev/'
jobs:
  status:
    name: Test if site is reachable
    runs-on: ubuntu-latest
    steps:
      - name: Get response code
        id: get-response
        run: |
          echo "::set-output name=code::$( \
          curl -IL $CHAT_URL 2> /dev/null \
          | head -n 1 \
          | cut  -d $' ' -f 2 )"
      - name: Validate app status
        run: |
          echo "${{ steps.get-response.outputs.code }}" \
          | grep -q '^2'
